language: node_js
node_js:
  - "8"
services:
  - docker
  - mongodb
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/6a3a7afc21be99f1afedbd2856d060a02755de6d/configure.sh | /bin/sh"
  - "curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl"
  - "chmod +x ./kubectl"
  - "sudo mv ./kubectl /usr/local/bin/kubectl"
  - "sudo snap install doctl"
  - "sudo snap connect doctl:kube-config"
  - "doctl kubernetes cluster kubeconfig save $KUBERNETES_CLUSTER"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg FONTAWESOMETOKEN=$FONTAWESOMETOKEN -t horizonshadow/famtime .
deploy:
  provider: script
  script: docker push horizonshadow/famtime
  on:
    branch: master